name: first-worflow

run-name: ${{ github.actor }} is learning GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Output
        run: echo "${{ github.ref }}"
