name: first-worflow

run-name: nodejs flow

on: [push, workflow_dispatch]

jobs:
  build:
    defaults:
      run:
        working-directory: app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: npm install
        run: |
          npm install
          npm run build

  test:
    defaults:
      run:
        working-directory: app
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        uses: npm run test

  lint:
    defaults:
      run:
        working-directory: app
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        uses: npm run lint
